apiVersion: v1
kind: Service
metadata:
  name: readmission-service
  labels:
    app: readmission-api
spec:
  selector:
    app: readmission-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

